### ISSUE TITLE
Tests don't work anymore

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/js-ajax-hitting-apis-lab#1]
Github's object that it returns no longer has name fields for the user, so that test fails. In addition, the tests that test the links for getCommits and getBranches also don't work properly.

**Comment by bhollan** [comment]
Can you provide more details?  Or code perhaps?  Maybe an example of a comparison of what was/is/should-be returned?

**Comment by dkStephanos** [comment]
Just looked back over that lab. I was able to get all the tests passing now
that I have a little more experience with AJAX. I had thought the API had
changed drastically since the lesson was written, but I think I am wrong
now. Sorry about that, haha.

**Comment by bhollan** [comment]
No worries!  I don't have the rights to close this, but you can close it if you think your concerns have been addressed.  Thanks for flagging it anyways!
