### ISSUE TITLE
jsdom Module Needs To Be Updated

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/js-ajax-hitting-apis-lab#4]
When installing the node modules for this lab, the `mocha-jsdom@1.2.0` module fails to install because it relies on a version of jsdom that is at least 10.0.0. 

Replacing the version number of jsdom in the package.json file for this lab and then running `npm install` fixes this issue.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ecssiah.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
